### ISSUE TITLE
[macOS] Window interaction stopping when shimeji is clicked

### ISSUE THREAD

**Issue by LavenderSnek** [LavenderSnek/ShimejiEE-cross-platform#14]
ActiveIE should ignore all windows from shimeji (also fixes crash when mascot tries to move own window). Similar to original mac JNA implementation

The existing implementation of just checking if the app has a bundle no longer works. The goal was to get it work properly when multiple instances of shimeji were running (and therefore did not use pid).

Might need to look into other options such as the Quartz APIs.

**Comment by rei-230** [comment]
Sorry to bother you! 
I really appreciate you making this shimejiee port, I'm very happy to be able to use it on macOS, it's just that I'm not familiar with the code at all so…. I want to know if there is any chance of this bug being fixed? 
(My translation may not be very accurate, I'm sorry，and thanks again ！)

**Comment by LavenderSnek** [comment]
It's because [this trick](https://github.com/LavenderSnek/ShimejiEE-cross-platform/blob/ed92d64329543a6299370f58a41dc3cc51b7cf5b/src/main/native/macjni/src/environment/ShimejiEnvironment.m#L92) no longer works.
The fix would either be comparing the PID (only works for one instance) or hardcoding the ShimejiEE title. I plan to fix it at some point.

**Comment by rei-230** [comment]
oh…I see ，Thank you answering my question！
appreciate you do for it again ，Looking forward to your future fix plan ^ ^！
