### ISSUE TITLE
is there any way to activate interactive windows?

### ISSUE THREAD

**Issue by r3xc0re** [LavenderSnek/ShimejiEE-cross-platform#4]
not really an issue I guess but I can't seem to find the "settings" to activate interactive windows. help with my issue would be great, thanks! :)

**Comment by LavenderSnek** [comment]
It should be enabled by default on the latest version of shimeji. 
The setting is in the menubar menu at `Allowed Behaviours > Throwing Windows`

Keep in mind that you have to click onto a window after shimeji is launched for it to be detected (and full-screened/maximized windows are ignored!)

Please add your system information if you continue to have issues.
